export const mockPointsTable = {
  standings: [
    {
      id: 7,
      position: 1,
      team: "Punjab Kings",
      matches: 14,
      wins: 13,
      losses: 1,
      points: 26,
      netRunRate: 1.332,
    },
    {
      id: 2,
      position: 2,
      team: "Chennai Super Kings",
      matches: 14,
      wins: 11,
      losses: 3,
      points: 22,
      netRunRate: 0.354,
    },
    {
      id: 9,
      position: 3,
      team: "Gujarat Titans",
      matches: 14,
      wins: 11,
      losses: 3,
      points: 22,
      netRunRate: 0.046,
    },
    {
      id: 10,
      position: 4,
      team: "Lucknow Super Giants",
      matches: 14,
      wins: 9,
      losses: 5,
      points: 18,
      netRunRate: 1.06,
    },
    {
      id: 5,
      position: 5,
      team: "Sunrisers Hyderabad",
      matches: 14,
      wins: 9,
      losses: 5,
      points: 18,
      netRunRate: 0.288,
    },
    {
      id: 4,
      position: 6,
      team: "Royal Challengers Bengaluru",
      matches: 14,
      wins: 9,
      losses: 5,
      points: 18,
      netRunRate: 0.014,
    },
    {
      id: 6,
      position: 7,
      team: "Kolkata Knight Riders",
      matches: 14,
      wins: 8,
      losses: 6,
      points: 16,
      netRunRate: 0.536,
    },
    {
      id: 8,
      position: 8,
      team: "Rajasthan Royals",
      matches: 14,
      wins: 8,
      losses: 6,
      points: 16,
      netRunRate: 0.474,
    },
    {
      id: 3,
      position: 9,
      team: "Mumbai Indians",
      matches: 14,
      wins: 7,
      losses: 7,
      points: 14,
      netRunRate: 0.732,
    },
    {
      id: 1,
      position: 10,
      team: "Delhi Capitals",
      matches: 14,
      wins: 6,
      losses: 8,
      points: 12,
      netRunRate: -0.159,
    },
  ],
};
