export const mockSchedule = {
  schedules: [
    {
      matchNumber: "match-0",
      team1: "Royal Challengers Bengaluru",
      team2: "Kolkata Knight Riders",
      date: "7 May",
      time: "7:30 PM",
      venue: "Bengaluru",
      day: "Wednesday",
    },
    {
      matchNumber: "match-1",
      team1: "Sunrisers Hyderabad",
      team2: "Delhi Capitals",
      date: "8 May",
      time: "7:30 PM",
      venue: "Hyderabad",
      day: "Thursday",
    },
    {
      matchNumber: "match-2",
      team1: "Punjab Kings",
      team2: "Sunrisers Hyderabad",
      date: "9 May",
      time: "7:30 PM",
      venue: "Mohali",
      day: "Friday",
    },
    {
      matchNumber: "match-3",
      team1: "Mumbai Indians",
      team2: "Lucknow Super Giants",
      date: "10 May",
      time: "7:30 PM",
      venue: "Mumbai",
      day: "Saturday",
    },
    {
      matchNumber: "match-4",
      team1: "Rajasthan Royals",
      team2: "Mumbai Indians",
      date: "11 May",
      time: "7:30 PM",
      venue: "Jaipur",
      day: "Sunday",
    },
    {
      matchNumber: "match-5",
      team1: "Delhi Capitals",
      team2: "Gujarat Titans",
      date: "12 May",
      time: "7:30 PM",
      venue: "Delhi",
      day: "Monday",
    },
    {
      matchNumber: "match-6",
      team1: "Sunrisers Hyderabad",
      team2: "Chennai Super Kings",
      date: "13 May",
      time: "7:30 PM",
      venue: "Hyderabad",
      day: "Tuesday",
    },
  ],
};
